/** AI-помощник, анализ фото, нормативная база, анализ происшествий, настройки. [ru, kz, en] */
export const aitools = {
  'as.title': ['AI-помощник спасателя', 'Құтқарушының AI-көмекшісі', 'Rescuer AI assistant'],
  'as.subtitle': ['Опишите обстановку — помощник структурирует оценку в 9 разделах и разделит факты, допущения и рекомендации', 'Жағдайды сипаттаңыз — көмекші бағалауды 9 бөлімге құрылымдап, фактілерді, болжамдар мен ұсынымдарды ажыратады', 'Describe the situation — the assistant structures an assessment in 9 sections and separates facts, assumptions and recommendations'],
  'as.new': ['Новый диалог', 'Жаңа диалог', 'New conversation'],
  'as.emptyTitle': ['Опишите происшествие', 'Оқиғаны сипаттаңыз', 'Describe the incident'],
  'as.emptyText': ['Укажите тип, этаж/площадь, людей, погоду. Чего не хватает — помощник спросит в разделе «Недостающая информация».', 'Түрін, қабатын/аумағын, адамдарды, ауа райын көрсетіңіз. Жетіспейтінін көмекші «Жетіспейтін ақпарат» бөлімінде сұрайды.', 'Give the type, floor/area, people and weather. Anything missing will be asked in the "Missing information" section.'],
  'as.placeholder': ['Опишите ситуацию: что произошло, где, этаж, люди, погода…', 'Жағдайды сипаттаңыз: не болды, қайда, қабат, адамдар, ауа райы…', 'Describe the situation: what happened, where, floor, people, weather…'],
  'as.send': ['Отправить', 'Жіберу', 'Send'],
  'as.thinking': ['Анализ обстановки · поиск в нормативной базе…', 'Жағдайды талдау · нормативтік базадан іздеу…', 'Analysing the situation · searching the regulations…'],
  'as.assessment': ['Оценка обстановки', 'Жағдайды бағалау', 'Situation assessment'],
  'as.facts': ['Факты, извлеченные из сообщения', 'Хабарламадан алынған фактілер', 'Facts extracted from the message'],
  'as.s1': ['Классификация ситуации', 'Жағдайды жіктеу', 'Classification'],
  'as.s2': ['Уровень угрозы', 'Қауіп деңгейі', 'Threat level'],
  'as.s3': ['Основные опасности', 'Негізгі қауіптер', 'Main hazards'],
  'as.s4': ['Возможные пострадавшие', 'Ықтимал зардап шеккендер', 'Possible casualties'],
  'as.s5': ['Необходимые силы и средства', 'Қажетті күштер мен құралдар', 'Required forces and resources'],
  'as.s6': ['Рекомендуемая последовательность действий', 'Ұсынылатын әрекеттер реті', 'Recommended sequence of actions'],
  'as.s7': ['Меры безопасности л/с', 'Жеке құрам қауіпсіздігі шаралары', 'Crew safety measures'],
  'as.s8': ['Недостающая информация', 'Жетіспейтін ақпарат', 'Missing information'],
  'as.s9': ['Нормативные документы', 'Нормативтік құжаттар', 'Regulations'],
  'as.confidence': ['Уверенность классификации: {p} %', 'Жіктеу сенімділігі: {p} %', 'Classification confidence: {p} %'],
  'as.prio.immediate': ['Немедленно', 'Дереу', 'Immediate'],
  'as.prio.high': ['Высокий', 'Жоғары', 'High'],
  'as.prio.normal': ['Обычный', 'Қалыпты', 'Normal'],
  'as.official': ['ОФИЦИАЛЬНЫЙ', 'РЕСМИ', 'OFFICIAL'],
  'as.demoDoc': ['ДЕМО, условный текст', 'ДЕМО, шартты мәтін', 'DEMO, placeholder text'],
  'as.proximity': ['близость {s}', 'жақындық {s}', 'similarity {s}'],
  'as.citeMeta': ['Источник: {s} · Раздел: {r} · Пункт: {c} · Стр.: {p}', 'Дереккөз: {s} · Бөлім: {r} · Тармақ: {c} · Бет: {p}', 'Source: {s} · Section: {r} · Clause: {c} · Page: {p}'],
  'as.ex1': ['Пожар в пятиэтажном доме на 3 этаже. Сильное задымление, могут быть люди, ветер 12 м/с.', 'Бес қабатты үйдің 3-қабатында өрт. Қатты түтін, адамдар болуы мүмкін, жел 12 м/с.', 'Fire on the 3rd floor of a five-storey building. Heavy smoke, people may be inside, wind 12 m/s.'],
  'as.ex2': ['ДТП на трассе, автобус опрокинулся, есть зажатые пострадавшие, ночь.', 'Трассада ЖКО, автобус аударылды, қысылып қалған зардап шеккендер бар, түн.', 'Road accident on a highway, a bus overturned, casualties trapped, night.'],
  'as.ex3': ['Паводок, подтоплено 20 домов, в домах остались 15 человек, +2 °C.', 'Су тасқыны, 20 үйді су басты, үйлерде 15 адам қалды, +2 °C.', 'Flood: 20 houses flooded, 15 people still inside, +2 °C.'],
  'as.ex4': ['Утечка аммиака на холодильной установке предприятия, ветер 5 м/с.', 'Кәсіпорынның тоңазытқыш қондырғысында аммиак ағуы, жел 5 м/с.', 'Ammonia leak at a plant refrigeration unit, wind 5 m/s.'],
  'as.ex5': ['Степной пожар 60 га, сильный ветер в сторону поселка, рядом ЛЭП.', 'Дала өрті 60 га, кентке қарай күшті жел, жанында ЭБЖ.', 'Steppe fire, 60 ha, strong wind towards a village, power line nearby.'],

  'ph.title': ['Анализ фото с места происшествия', 'Оқиға орнындағы фотоны талдау', 'On-scene photo analysis'],
  'ph.subtitle': ['Изображение → backend → модель компьютерного зрения → структурированный результат по 8 классам опасностей', 'Сурет → backend → компьютерлік көру моделі → 8 қауіп класы бойынша құрылымдық нәтиже', 'Image → backend → computer vision model → structured result across 8 hazard classes'],
  'ph.other': ['Другое фото', 'Басқа фото', 'Another photo'],
  'ph.step1': ['Загрузка', 'Жүктеу', 'Upload'],
  'ph.step2demo': ['Анализ пикселей (браузер)', 'Пиксельдерді талдау (браузер)', 'Pixel analysis (browser)'],
  'ph.step3demo': ['Демо-классификация', 'Демо-жіктеу', 'Demo classification'],
  'ph.step2live': ['Отправка на backend', 'Backend-ке жіберу', 'Send to backend'],
  'ph.step3live': ['Модель компьютерного зрения', 'Компьютерлік көру моделі', 'Computer vision model'],
  'ph.step4': ['Структурированный результат', 'Құрылымдық нәтиже', 'Structured result'],
  'ph.drop': ['Перетащите фото сюда или выберите файл', 'Фотоны осында сүйреңіз немесе файлды таңдаңыз', 'Drag a photo here or choose a file'],
  'ph.formats': ['JPEG, PNG, WEBP до {mb} МБ. Изображение {where}.', 'JPEG, PNG, WEBP, {mb} МБ-қа дейін. Сурет {where}.', 'JPEG, PNG, WEBP up to {mb} MB. The image {where}.'],
  'ph.whereDemo': ['обрабатывается только в браузере', 'тек браузерде өңделеді', 'is processed only in the browser'],
  'ph.whereLive': ['передается на backend QUTQAR AI', 'QUTQAR AI backend-іне жіберіледі', 'is sent to the QUTQAR AI backend'],
  'ph.choose': ['Выбрать фото', 'Фото таңдау', 'Choose photo'],
  'ph.badType': ['Поддерживаются изображения JPEG, PNG, WEBP.', 'JPEG, PNG, WEBP суреттері қолдау көрсетіледі.', 'Only JPEG, PNG and WEBP images are supported.'],
  'ph.tooBig': ['Файл больше {mb} МБ.', 'Файл {mb} МБ-тан үлкен.', 'The file is larger than {mb} MB.'],
  'ph.analyze': ['Анализировать', 'Талдау', 'Analyse'],
  'ph.reanalyze': ['Повторить анализ', 'Талдауды қайталау', 'Analyse again'],
  'ph.original': ['Исходное изображение', 'Бастапқы сурет', 'Original image'],
  'ph.overlay': ['Слой AI-детекции', 'AI-анықтау қабаты', 'AI detection overlay'],
  'ph.result': ['Результат анализа', 'Талдау нәтижесі', 'Analysis result'],
  'ph.wait': ['Загрузите фото и нажмите «Анализировать».', 'Фото жүктеп, «Талдау» түймесін басыңыз.', 'Upload a photo and press "Analyse".'],
  'ph.processing': ['Обработка изображения…', 'Сурет өңделуде…', 'Processing the image…'],
  'ph.overall': ['Общий уровень угрозы', 'Жалпы қауіп деңгейі', 'Overall threat level'],
  'ph.detections': ['Обнаруженные опасности', 'Анықталған қауіптер', 'Detected hazards'],
  'ph.noDetections': ['Опасностей не выявлено.', 'Қауіп анықталмады.', 'No hazards identified.'],
  'ph.detected': ['ОБНАРУЖЕНО', 'АНЫҚТАЛДЫ', 'DETECTED'],
  'ph.possible': ['ВОЗМОЖНО', 'МҮМКІН', 'POSSIBLE'],
  'ph.simulated': ['СИМУЛЯЦИЯ', 'МОДЕЛЬДЕУ', 'SIMULATED'],
  'ph.notDetected': ['Не обнаружено', 'Анықталмады', 'Not detected'],
  'ph.unknown': ['Не определено', 'Анықталмаған', 'Undetermined'],
  'ph.why': ['Почему важно', 'Неге маңызды', 'Why it matters'],
  'ph.uncertainty': ['Неопределенность', 'Белгісіздік', 'Uncertainty'],
  'ph.unc.value': ['± {u} п. п. (диапазон {a}–{b} %)', '± {u} п. т. ({a}–{b} % аралығы)', '± {u} pp (range {a}–{b} %)'],
  'ph.unc.none': ['не оценивается — значение смоделировано', 'бағаланбайды — мән модельденген', 'not assessed — the value is simulated'],
  'ph.basis.model': ['модель CV', 'CV моделі', 'CV model'],
  'ph.basis.heuristic': ['эвристика цвета', 'түс эвристикасы', 'colour heuristic'],
  'ph.basis.simulated': ['симуляция', 'модельдеу', 'simulation'],
  'ph.categories': ['Все 8 классов', 'Барлық 8 класс', 'All 8 classes'],
  'ph.recs': ['Рекомендации', 'Ұсынымдар', 'Recommendations'],
  'ph.limits': ['Ограничения', 'Шектеулер', 'Limitations'],
  'ph.meta': ['Модель: {m} · {d} · {w}×{h}', 'Модель: {m} · {d} · {w}×{h}', 'Model: {m} · {d} · {w}×{h}'],
  'ph.legend': ['ОБНАРУЖЕНО — уверенный признак; ВОЗМОЖНО — слабый признак; СИМУЛЯЦИЯ — в DEMO этот класс не распознается, область смоделирована (пунктир).', 'АНЫҚТАЛДЫ — сенімді белгі; МҮМКІН — әлсіз белгі; МОДЕЛЬДЕУ — DEMO-да бұл класс танылмайды, аймақ модельденген (пунктир).', 'DETECTED — strong signal; POSSIBLE — weak signal; SIMULATED — this class is not recognised in DEMO, the area is simulated (dashed).'],

  'kb.title': ['Нормативная база (RAG)', 'Нормативтік база (RAG)', 'Regulations knowledge base (RAG)'],
  'kb.subtitle': ['Ответы только по загруженным документам, с указанием источника, документа, раздела и пункта/страницы. Цитаты не генерируются.', 'Жауаптар тек жүктелген құжаттар бойынша, дереккөз, құжат, бөлім және тармақ/бет көрсетіледі. Дәйексөздер ойдан құрастырылмайды.', 'Answers only from uploaded documents, citing source, document, section and clause/page. Citations are never invented.'],
  'kb.upload': ['Загрузить документ', 'Құжат жүктеу', 'Upload document'],
  'kb.st1': ['Документ', 'Құжат', 'Document'],
  'kb.st2': ['Извлечение текста', 'Мәтінді шығару', 'Text extraction'],
  'kb.st3': ['Чанкинг', 'Бөлшектеу', 'Chunking'],
  'kb.st4': ['Эмбеддинги', 'Эмбеддингтер', 'Embeddings'],
  'kb.st5': ['Векторный поиск', 'Векторлық іздеу', 'Vector search'],
  'kb.st6': ['Ответ со ссылками', 'Сілтемелері бар жауап', 'Cited answer'],
  'kb.pipeline': ['Эмбеддинги: {e} · фрагментов: {c} · порог близости: {t} · официальных документов:', 'Эмбеддингтер: {e} · фрагменттер: {c} · жақындық шегі: {t} · ресми құжаттар:', 'Embeddings: {e} · chunks: {c} · similarity threshold: {t} · official documents:'],
  'kb.placeholder': ['Вопрос по нормативной базе…', 'Нормативтік база бойынша сұрақ…', 'Question about the regulations…'],
  'kb.find': ['Найти', 'Табу', 'Search'],
  'kb.answer': ['Ответ', 'Жауап', 'Answer'],
  'kb.sources': ['Источники (найденные фрагменты)', 'Дереккөздер (табылған фрагменттер)', 'Sources (retrieved chunks)'],
  'kb.src': ['Источник', 'Дереккөз', 'Source'],
  'kb.doc': ['Документ', 'Құжат', 'Document'],
  'kb.section': ['Раздел', 'Бөлім', 'Section'],
  'kb.clausePage': ['Пункт / страница', 'Тармақ / бет', 'Clause / page'],
  'kb.searchStats': ['Поиск: {c} фрагментов · top-{k} · {e} · порог {t}', 'Іздеу: {c} фрагмент · top-{k} · {e} · шегі {t}', 'Search: {c} chunks · top-{k} · {e} · threshold {t}'],
  'kb.docs': ['Проиндексированные документы', 'Индекстелген құжаттар', 'Indexed documents'],
  'kb.chunks': ['{n} фрагм.', '{n} фрагм.', '{n} chunks'],
  'kb.pages': ['{n} стр.', '{n} бет', '{n} pp.'],
  'kb.unofficial': ['НЕОФИЦИАЛЬНЫЙ', 'РЕСМИ ЕМЕС', 'UNOFFICIAL'],
  'kb.noDocs': ['Документы не загружены. Официальный источник не подключен.', 'Құжаттар жүктелмеген. Ресми дереккөз қосылмаған.', 'No documents uploaded. No official source is connected.'],
  'kb.delete': ['Удалить {t}', '{t} жою', 'Delete {t}'],
  'kb.ex1': ['Какие действия выполняются при пожаре в многоэтажном здании?', 'Көпқабатты ғимараттағы өрт кезінде қандай әрекеттер орындалады?', 'What actions are taken for a fire in a multi-storey building?'],
  'kb.ex2': ['Требования к работе в задымленной среде', 'Түтінді ортада жұмыс істеуге қойылатын талаптар', 'Requirements for working in smoke'],
  'kb.ex3': ['Работа на воде при паводке', 'Су тасқыны кезінде суда жұмыс істеу', 'Water operations during floods'],
  'kb.ex4': ['Порядок деблокирования при ДТП', 'ЖКО кезінде бұғаттан шығару тәртібі', 'Extrication procedure at road accidents'],
  'kb.up.title': ['Загрузка документа в базу знаний', 'Білім базасына құжат жүктеу', 'Upload a document to the knowledge base'],
  'kb.up.go': ['Загрузить и проиндексировать', 'Жүктеу және индекстеу', 'Upload and index'],
  'kb.up.busy': ['Индексация…', 'Индекстеу…', 'Indexing…'],
  'kb.up.types': ['Типы: законы, правила, приказы, инструкции, методические материалы.', 'Түрлері: заңдар, ережелер, бұйрықтар, нұсқаулықтар, әдістемелік материалдар.', 'Types: laws, rules, orders, instructions, methodological materials.'],
  'kb.up.demo': ['В DEMO MODE: только .txt/.md, индекс в браузере до перезагрузки, документ не может быть официальным.', 'DEMO MODE-та: тек .txt/.md, индекс браузерде қайта жүктелгенге дейін, құжат ресми бола алмайды.', 'In DEMO MODE: .txt/.md only, indexed in the browser until reload, cannot be marked official.'],
  'kb.up.live': ['Форматы .txt, .md, .pdf (текстовый слой), .docx.', 'Форматтар: .txt, .md, .pdf (мәтін қабаты), .docx.', 'Formats: .txt, .md, .pdf (text layer), .docx.'],
  'kb.up.file': ['Файл', 'Файл', 'File'],
  'kb.up.name': ['Название документа', 'Құжат атауы', 'Document title'],
  'kb.up.cat': ['Категория', 'Санат', 'Category'],
  'kb.up.source': ['Источник', 'Дереккөз', 'Source'],
  'kb.up.sourcePh': ['Издатель, №, дата, ИПС «Әділет»', 'Шығарушы, №, күні, «Әділет» АҚЖ', 'Issuer, number, date, Adilet database'],
  'kb.up.official': ['Официальный документ', 'Ресми құжат', 'Official document'],
  'kb.up.officialHint': ['Отмечайте только сверенные тексты из официального источника. Только такие документы снимают пометку «Официальный источник не подключен».', 'Тек ресми дереккөзден салыстырылған мәтіндерді белгілеңіз. Тек осындай құжаттар «Ресми дереккөз қосылмаған» белгісін алып тастайды.', 'Only mark texts verified against an official source. Only such documents remove the "No official source connected" notice.'],
  'kb.up.token': ['Токен администратора (если задан KB_ADMIN_TOKEN)', 'Әкімші токені (KB_ADMIN_TOKEN берілсе)', 'Admin token (if KB_ADMIN_TOKEN is set)'],
  'kb.up.noFile': ['Выберите файл', 'Файлды таңдаңыз', 'Choose a file'],
  'kb.up.needSource': ['Для официального документа укажите источник: издатель, реквизиты, дата.', 'Ресми құжат үшін дереккөзді көрсетіңіз: шығарушы, деректемелер, күні.', 'For an official document, give the source: issuer, reference, date.'],
  'kb.up.failed': ['Загрузка не выполнена', 'Жүктеу орындалмады', 'Upload failed'],
  'kb.cat.laws': ['Законы', 'Заңдар', 'Laws'],
  'kb.cat.rules': ['Правила', 'Ережелер', 'Rules'],
  'kb.cat.orders': ['Приказы', 'Бұйрықтар', 'Orders'],
  'kb.cat.instr': ['Инструкции', 'Нұсқаулықтар', 'Instructions'],
  'kb.cat.method': ['Методические материалы', 'Әдістемелік материалдар', 'Methodological materials'],

  'aar.title': ['Анализ происшествий (after-action review)', 'Оқиғаларды талдау (after-action review)', 'Incident analysis (after-action review)'],
  'aar.subtitle': ['Загрузите донесение — система построит хронологию и выделит решения, задержки, риски, ресурсы, связь и уроки', 'Баяндаманы жүктеңіз — жүйе хронология құрып, шешімдерді, кідірістерді, тәуекелдерді, ресурстарды, байланыс пен сабақтарды бөліп көрсетеді', 'Upload a report — the system builds a timeline and highlights decisions, delays, risks, resources, communications and lessons'],
  'aar.label': ['Аналитическая помощь, а не официальное расследование.', 'Талдамалық көмек, ресми тергеу емес.', 'Analytical assistance, not an official investigation.'],
  'aar.labelText': ['Выводы формируются автоматически по тексту документа и требуют проверки. Они не устанавливают вину и не заменяют служебную проверку или расследование в установленном порядке.', 'Қорытындылар құжат мәтіні бойынша автоматты түрде жасалады және тексеруді қажет етеді. Олар кінәні анықтамайды және белгіленген тәртіппен жүргізілетін қызметтік тексеруді немесе тергеуді алмастырмайды.', 'Findings are generated automatically from the document text and must be verified. They do not establish fault and do not replace an internal inquiry or a formal investigation.'],
  'aar.tab.upload': ['Загрузить отчет', 'Есепті жүктеу', 'Upload report'],
  'aar.tab.text': ['Вставить текст', 'Мәтінді қою', 'Paste text'],
  'aar.tab.archive': ['Архив (демо)', 'Мұрағат (демо)', 'Archive (demo)'],
  'aar.uploadHint': ['Донесение, журнал РТП или отчет с временными метками (ЧЧ:ММ).', 'Баяндама, ӨСБ журналы немесе уақыт белгілері бар есеп (СС:ММ).', 'A report, incident commander log or document with timestamps (HH:MM).'],
  'aar.formatsDemo': ['.txt, .md (в DEMO MODE — обработка в браузере)', '.txt, .md (DEMO MODE-та — браузерде өңдеу)', '.txt, .md (processed in the browser in DEMO MODE)'],
  'aar.formatsLive': ['.txt, .md, .pdf, .docx (извлечение текста на backend)', '.txt, .md, .pdf, .docx (мәтін backend-те шығарылады)', '.txt, .md, .pdf, .docx (text extracted on the backend)'],
  'aar.choose': ['Выбрать файл', 'Файлды таңдау', 'Choose file'],
  'aar.sample': ['Открыть пример донесения', 'Баяндама үлгісін ашу', 'Open a sample report'],
  'aar.insertSample': ['Вставить пример', 'Үлгіні қою', 'Insert sample'],
  'aar.run': ['Проанализировать', 'Талдау', 'Analyse'],
  'aar.docName': ['Название документа', 'Құжат атауы', 'Document title'],
  'aar.docText': ['Текст донесения', 'Баяндама мәтіні', 'Report text'],
  'aar.pdfDemo': ['PDF и DOCX извлекаются на backend. Выключите DEMO MODE или загрузите .txt/.md.', 'PDF және DOCX backend-те шығарылады. DEMO MODE өшіріңіз немесе .txt/.md жүктеңіз.', 'PDF and DOCX are extracted on the backend. Turn off DEMO MODE or upload .txt/.md.'],
  'aar.badFile': ['Поддерживаются .txt, .md, а через backend — также .pdf и .docx.', '.txt, .md, ал backend арқылы .pdf және .docx қолдау көрсетіледі.', 'Supported: .txt, .md, and via the backend also .pdf and .docx.'],
  'aar.tooBig': ['Файл больше 15 МБ.', 'Файл 15 МБ-тан үлкен.', 'The file is larger than 15 MB.'],
  'aar.loading': ['Извлечение хронологии и анализ…', 'Хронологияны шығару және талдау…', 'Extracting the timeline and analysing…'],
  'aar.badge': ['АНАЛИТИЧЕСКАЯ ПОМОЩЬ', 'ТАЛДАМАЛЫҚ КӨМЕК', 'ANALYTICAL ASSISTANCE'],
  'aar.source': ['Источник: {s}', 'Дереккөз: {s}', 'Source: {s}'],
  'aar.timeline': ['Хронология', 'Хронология', 'Timeline'],
  'aar.noTimeline': ['Временные метки не найдены.', 'Уақыт белгілері табылмады.', 'No timestamps found.'],
  'aar.line': ['строка {n}', '{n}-жол', 'line {n}'],
  'aar.decisions': ['Ключевые решения', 'Негізгі шешімдер', 'Key decisions'],
  'aar.delays': ['Задержки', 'Кідірістер', 'Delays'],
  'aar.risks': ['Риски', 'Тәуекелдер', 'Risks'],
  'aar.comms': ['Проблемы связи', 'Байланыс мәселелері', 'Communication issues'],
  'aar.resources': ['Использование сил и средств', 'Күштер мен құралдарды пайдалану', 'Use of forces and resources'],
  'aar.lessons': ['Уроки и рекомендации', 'Сабақтар мен ұсынымдар', 'Lessons and recommendations'],
  'aar.none': ['В тексте не выделено.', 'Мәтінде анықталмады.', 'Nothing identified in the text.'],
  'aar.dataQuality': ['Полнота исходных данных', 'Бастапқы деректердің толықтығы', 'Completeness of the source data'],
  'aar.resItem': ['Ресурс', 'Ресурс', 'Resource'],
  'aar.resCount': ['Кол-во', 'Саны', 'Count'],
  'aar.resWhere': ['Где', 'Қайда', 'Where'],

  'set.title': ['Настройки', 'Баптаулар', 'Settings'],
  'set.subtitle': ['Параметры интерфейса и подключения. Хранятся только в этом браузере.', 'Интерфейс және қосылым параметрлері. Тек осы браузерде сақталады.', 'Interface and connection options. Stored only in this browser.'],
  'set.lang': ['Язык интерфейса', 'Интерфейс тілі', 'Interface language'],
  'set.langHint': ['Переводит весь интерфейс; даты — в формате РК (UTC+5).', 'Бүкіл интерфейсті аударады; күндер — ҚР форматында (UTC+5).', 'Translates the entire interface; dates use Kazakhstan format (UTC+5).'],
  'set.map': ['Картографическая подложка', 'Картографиялық негіз', 'Base map'],
  'set.mapHint': ['Без интернета показывается схематичный контур РК.', 'Интернетсіз ҚР-дың сызбалық контуры көрсетіледі.', 'Without internet, a schematic outline of Kazakhstan is shown.'],
  'set.map.light': ['Светлая (CARTO)', 'Ашық (CARTO)', 'Light (CARTO)'],
  'set.map.osm': ['OpenStreetMap', 'OpenStreetMap', 'OpenStreetMap'],
  'set.map.dark': ['Темная (CARTO)', 'Күңгірт (CARTO)', 'Dark (CARTO)'],
  'set.notif': ['Уведомления', 'Хабарламалар', 'Notifications'],
  'set.notifHint': ['Отображение оперативных уведомлений в шапке.', 'Жедел хабарламаларды тақырыпшада көрсету.', 'Show operational notifications in the header.'],
  'set.notifLabel': ['Показывать уведомления о происшествиях', 'Оқиғалар туралы хабарламаларды көрсету', 'Show incident notifications'],
  'set.operator': ['Оператор', 'Оператор', 'Operator'],
  'set.operatorHint': ['Имя используется в профиле, отчетах и тренажере.', 'Аты профильде, есептерде және тренажерде қолданылады.', 'Used in the profile, reports and the simulator.'],
  'set.demo': ['DEMO MODE', 'DEMO MODE', 'DEMO MODE'],
  'set.demoHint': ['Глобальный режим демонстрации. Можно переключить и в шапке.', 'Жаһандық көрсету режимі. Тақырыпшада да ауыстыруға болады.', 'Global demonstration mode. Can also be toggled in the header.'],
  'set.demoOn': ['DEMO MODE включен', 'DEMO MODE қосулы', 'DEMO MODE on'],
  'set.demoText': ['вымышленные данные, ответы AI моделируются в браузере, сеть не используется. Каждый экран помечен баннером DEMO.', 'ойдан шығарылған деректер, AI жауаптары браузерде модельденеді, желі пайдаланылмайды. Әр экран DEMO баннерімен белгіленген.', 'fictional data; AI answers are simulated in the browser; no network is used. Every screen carries a DEMO banner.'],
  'set.demoOff': ['Выключено: данные и ответы только от backend; при его недоступности показывается ошибка, подмены демо-данными нет.', 'Өшірулі: деректер мен жауаптар тек backend-тен; ол қолжетімсіз болса қате көрсетіледі, демо-деректермен ауыстыру жоқ.', 'Off: data and answers come only from the backend; if unavailable an error is shown — no demo substitution.'],
  'set.speed': ['Скорость демо-ответов', 'Демо-жауаптар жылдамдығы', 'Demo answer speed'],
  'set.speed.real': ['Реалистичная', 'Шынайы', 'Realistic'],
  'set.speed.fast': ['Быстрая (для показа)', 'Жылдам (көрсету үшін)', 'Fast (for demos)'],
  'set.backend': ['Backend и AI-модель', 'Backend және AI-модель', 'Backend and AI model'],
  'set.backendHint': ['Ключи и адрес модели задаются только на сервере (server/.env).', 'Кілттер мен модель мекенжайы тек серверде беріледі (server/.env).', 'Keys and model address are set only on the server (server/.env).'],
  'set.address': ['Адрес backend', 'Backend мекенжайы', 'Backend address'],
  'set.sameOrigin': ['тот же домен (/api)', 'сол домен (/api)', 'same origin (/api)'],
  'set.state': ['Состояние', 'Күйі', 'State'],
  'set.st.unknown': ['не проверялось', 'тексерілмеген', 'not checked'],
  'set.st.checking': ['проверка…', 'тексерілуде…', 'checking…'],
  'set.st.online': ['на связи', 'байланыста', 'online'],
  'set.st.offline': ['недоступен', 'қолжетімсіз', 'unavailable'],
  'set.model': ['AI-модель', 'AI-модель', 'AI model'],
  'set.vision': ['Vision', 'Vision', 'Vision'],
  'set.kbStat': ['База знаний', 'Білім базасы', 'Knowledge base'],
  'set.kbValue': ['{d} док. / {o} офиц. / {c} фрагм.', '{d} құж. / {o} ресми / {c} фрагм.', '{d} docs / {o} official / {c} chunks'],
  'set.embeddings': ['Эмбеддинги', 'Эмбеддингтер', 'Embeddings'],
  'set.check': ['Проверить подключение', 'Қосылуды тексеру', 'Check connection'],
  'set.safety': ['Безопасность и ограничения', 'Қауіпсіздік және шектеулер', 'Security and limitations'],
  'set.s1': ['Ключи AI-провайдеров не хранятся во фронтенде: запросы идут через backend-прокси.', 'AI-провайдер кілттері фронтендте сақталмайды: сұраулар backend-прокси арқылы жүреді.', 'AI provider keys are never stored in the frontend: requests go through the backend proxy.'],
  'set.s2': ['В DEMO MODE все данные вымышлены и не являются данными МЧС РК.', 'DEMO MODE-та барлық деректер ойдан шығарылған және ҚР ТЖМ деректері емес.', 'In DEMO MODE all data is fictional and is not MChS RK data.'],
  'set.s3': ['AI не является органом МЧС РК; рекомендации — учебная и информационная помощь.', 'AI ҚР ТЖМ органы емес; ұсынымдар — оқу және ақпараттық көмек.', 'The AI is not an MChS RK authority; recommendations are training and information assistance.'],
  'set.s4': ['Приложение не выдумывает законы, контакты и оперативные сведения.', 'Қосымша заңдарды, байланыстарды және жедел мәліметтерді ойдан шығармайды.', 'The application never invents laws, contacts or operational information.'],
  'set.reset': ['Сбросить настройки', 'Баптауларды қалпына келтіру', 'Reset settings'],
  'set.resetTitle': ['Сбросить все настройки?', 'Барлық баптауларды қалпына келтіру керек пе?', 'Reset all settings?'],
  'set.resetText': ['Язык, подложка, имя оператора и режим вернутся к значениям по умолчанию.', 'Тіл, негіз, оператор аты және режим әдепкі мәндерге оралады.', 'Language, base map, operator name and mode will return to defaults.'],
} as const;
