/** Оболочка приложения: навигация, шапка, баннеры режимов, общие элементы интерфейса. [ru, kz, en] */
export const common = {
  // навигация
  'nav.dashboard': ['Оперативная обстановка', 'Жедел жағдай', 'Operations overview'],
  'nav.briefing': ['AI-брифинг', 'AI-брифинг', 'AI Briefing'],
  'nav.resources': ['Силы и средства', 'Күштер мен құралдар', 'Resource Manager'],
  'nav.assistant': ['AI-помощник', 'AI-көмекші', 'AI Assistant'],
  'nav.simulator': ['AI-тренажер ЧС', 'ТЖ AI-тренажері', 'AI Emergency Simulator'],
  'nav.photo': ['Анализ фото', 'Фото талдау', 'Photo Analysis'],
  'nav.map': ['Карта ЧС', 'ТЖ картасы', 'Emergency Map'],
  'nav.kb': ['Нормативная база', 'Нормативтік база', 'Regulations (RAG)'],
  'nav.analysis': ['Анализ происшествий', 'Оқиғаларды талдау', 'Incident Analysis'],
  'nav.report': ['Отчеты', 'Есептер', 'Reports'],
  'nav.settings': ['Настройки', 'Баптаулар', 'Settings'],
  'nav.presentation': ['Режим презентации', 'Презентация режимі', 'Presentation mode'],
  'nav.group.ops': ['Оперативная работа', 'Жедел жұмыс', 'Operations'],
  'nav.group.ai': ['AI-инструменты', 'AI-құралдар', 'AI tools'],
  'nav.group.training': ['Подготовка', 'Даярлық', 'Training'],
  'nav.group.system': ['Система', 'Жүйе', 'System'],
  'nav.menu': ['Открыть меню', 'Мәзірді ашу', 'Open menu'],
  'nav.close': ['Закрыть меню', 'Мәзірді жабу', 'Close menu'],

  // бренд и шапка
  'app.subtitle': ['Система интеллектуальной поддержки спасательных подразделений', 'Құтқару бөлімшелерін зияткерлік қолдау жүйесі', 'Intelligent decision support for rescue units'],
  'app.tagline': ['Прототип для Республики Казахстан', 'Қазақстан Республикасына арналған прототип', 'Prototype for the Republic of Kazakhstan'],
  'app.home': ['QUTQAR AI — на главную', 'QUTQAR AI — басты бетке', 'QUTQAR AI — home'],
  'header.notifications': ['Уведомления', 'Хабарламалар', 'Notifications'],
  'header.markAll': ['Прочитать все', 'Барлығын оқу', 'Mark all read'],
  'header.noNotif': ['Новых уведомлений нет', 'Жаңа хабарламалар жоқ', 'No new notifications'],
  'header.notifOff': ['Уведомления отключены в настройках', 'Хабарламалар баптауларда өшірілген', 'Notifications are disabled in settings'],
  'header.notifLive': ['Источник оперативных уведомлений не подключен', 'Жедел хабарламалар көзі қосылмаған', 'No operational notification source is connected'],
  'header.profile': ['Профиль', 'Профиль', 'Profile'],
  'header.role': ['Оперативный дежурный (DEMO)', 'Жедел кезекші (DEMO)', 'Duty officer (DEMO)'],
  'header.logout': ['Выйти', 'Шығу', 'Sign out'],
  'header.logoutTitle': ['Завершить сеанс?', 'Сеансты аяқтау керек пе?', 'End the session?'],
  'header.logoutText': ['В прототипе нет авторизации: выход очищает только открытые панели. Настройки сохраняются в этом браузере.', 'Прототипте авторизация жоқ: шығу тек ашық панельдерді жабады. Баптаулар осы браузерде сақталады.', 'The prototype has no authentication: signing out only closes open panels. Settings stay in this browser.'],
  'header.language': ['Язык интерфейса', 'Интерфейс тілі', 'Interface language'],
  'header.demoSwitch': ['Переключатель DEMO MODE', 'DEMO MODE ауыстырғышы', 'DEMO MODE switch'],
  'header.demoOnHint': ['DEMO MODE включен — нажмите, чтобы подключиться к backend', 'DEMO MODE қосулы — backend-ке қосылу үшін басыңыз', 'DEMO MODE is on — click to connect to the backend'],
  'header.liveHint': ['LIVE — нажмите, чтобы включить DEMO MODE', 'LIVE — DEMO MODE қосу үшін басыңыз', 'LIVE — click to enable DEMO MODE'],
  'header.confirmTitle': ['Выключить DEMO MODE?', 'DEMO MODE өшіру керек пе?', 'Turn off DEMO MODE?'],
  'header.confirm1': ['В режиме LIVE все запросы идут на backend QUTQAR AI (/api/*), который обращается к подключенной AI-модели.', 'LIVE режимінде барлық сұраулар QUTQAR AI backend-іне (/api/*) жіберіледі, ол қосылған AI-модельге жүгінеді.', 'In LIVE mode all requests go to the QUTQAR AI backend (/api/*), which calls the connected AI model.'],
  'header.confirm2': ['Если backend не запущен, функции покажут ошибку — демо-данные не подставляются.', 'Backend іске қосылмаса, функциялар қате көрсетеді — демо-деректер ауыстырылмайды.', 'If the backend is not running, features show an error — demo data is never substituted.'],
  'header.confirm3': ['Если на сервере не задан AI_API_KEY, ответы помечаются как «модель не подключена».', 'Серверде AI_API_KEY берілмесе, жауаптар «модель қосылмаған» деп белгіленеді.', 'If AI_API_KEY is not set on the server, answers are labelled "model not connected".'],
  'header.confirm4': ['Карта и дашборд покажут данные только при подключенном источнике оперативных данных.', 'Карта мен басқару тақтасы деректерді тек жедел деректер көзі қосылғанда көрсетеді.', 'The map and dashboard show data only when an operational data source is connected.'],
  'header.publicDemo': ['Публичная демо-версия: работает только в DEMO MODE (без backend и AI-ключей).', 'Жария демо-нұсқа: тек DEMO MODE-та жұмыс істейді (backend және AI кілттерінсіз).', 'Public demo build: runs in DEMO MODE only (no backend or AI keys).'],
  'header.stayDemo': ['Остаться в DEMO', 'DEMO-да қалу', 'Stay in DEMO'],
  'header.goLive': ['Подключиться к backend', 'Backend-ке қосылу', 'Connect to backend'],

  // баннеры режимов
  'mode.demo': ['DEMO MODE', 'DEMO MODE', 'DEMO MODE'],
  'mode.live': ['LIVE MODE', 'LIVE MODE', 'LIVE MODE'],
  'mode.demoBanner': ['Все данные вымышлены · ответы AI смоделированы · работает без интернета и backend.', 'Барлық деректер ойдан шығарылған · AI жауаптары модельденген · интернетсіз және backend-сіз жұмыс істейді.', 'All data is fictional · AI answers are simulated · works without internet or backend.'],
  'mode.demoStrong': ['Не является оперативной информацией МЧС РК.', 'ҚР ТЖМ жедел ақпараты болып табылмайды.', 'This is not operational MChS RK information.'],
  'mode.checking': ['Проверка подключения к backend…', 'Backend-ке қосылуды тексеру…', 'Checking backend connection…'],
  'mode.online': ['Backend на связи', 'Backend байланыста', 'Backend online'],
  'mode.ai': ['AI', 'AI', 'AI'],
  'mode.mock': ['модель не подключена (mock)', 'модель қосылмаған (mock)', 'model not connected (mock)'],
  'mode.rag': ['RAG', 'RAG', 'RAG'],
  'mode.ragOfficial': ['{n} офиц. док.', '{n} ресми құжат', '{n} official docs'],
  'mode.ragNone': ['официальные документы не загружены', 'ресми құжаттар жүктелмеген', 'no official documents loaded'],
  'mode.ops': ['Оперативные данные', 'Жедел деректер', 'Operational data'],
  'mode.connected': ['подключены', 'қосылған', 'connected'],
  'mode.notConnected': ['не подключены', 'қосылмаған', 'not connected'],
  'mode.offline': ['Backend недоступен: {e}. AI-функции вернут ошибку; включите DEMO MODE для демонстрации.', 'Backend қолжетімсіз: {e}. AI-функциялар қате қайтарады; көрсету үшін DEMO MODE қосыңыз.', 'Backend unavailable: {e}. AI features will return errors; enable DEMO MODE to demonstrate.'],
  'mode.recheck': ['проверить', 'тексеру', 'check'],
  'mode.recheckAria': ['Проверить подключение', 'Қосылуды тексеру', 'Check connection'],
  'mode.sideDemo': ['Вымышленные данные и симулированные ответы.', 'Ойдан шығарылған деректер және модельденген жауаптар.', 'Fictional data and simulated answers.'],
  'mode.sideLive': ['Данные и ответы — только от backend.', 'Деректер мен жауаптар — тек backend-тен.', 'Data and answers come only from the backend.'],
  'mode.sideLiveModel': ['LIVE · AI: модель', 'LIVE · AI: модель', 'LIVE · AI: model'],
  'mode.sideLiveMock': ['LIVE · AI: mock', 'LIVE · AI: mock', 'LIVE · AI: mock'],
  'mode.sideOffline': ['LIVE · backend недоступен', 'LIVE · backend қолжетімсіз', 'LIVE · backend unavailable'],
  'mode.watermark': ['DEMO · ВЫМЫШЛЕННЫЕ ДАННЫЕ', 'DEMO · ОЙДАН ШЫҒАРЫЛҒАН ДЕРЕКТЕР', 'DEMO · FICTIONAL DATA'],
  'mode.offlineNet': ['Нет подключения к интернету — DEMO MODE продолжает работать офлайн.', 'Интернет байланысы жоқ — DEMO MODE офлайн жұмысын жалғастыруда.', 'No internet connection — DEMO MODE keeps working offline.'],

  // бейджи происхождения ответа
  'badge.demo': ['DEMO · симуляция', 'DEMO · модельдеу', 'DEMO · simulated'],
  'badge.mock': ['BACKEND · модель не подключена', 'BACKEND · модель қосылмаған', 'BACKEND · model not connected'],
  'badge.live': ['LIVE · {m}', 'LIVE · {m}', 'LIVE · {m}'],
  'badge.training': ['DEMO / TRAINING', 'DEMO / TRAINING', 'DEMO / TRAINING'],
  'badge.provider': ['Провайдер: {p}; модель: {m}; {ms} мс', 'Провайдер: {p}; модель: {m}; {ms} мс', 'Provider: {p}; model: {m}; {ms} ms'],
  'stmt.fact': ['ФАКТ', 'ФАКТ', 'FACT'],
  'stmt.assumption': ['ДОПУЩЕНИЕ', 'БОЛЖАМ', 'ASSUMPTION'],
  'stmt.recommendation': ['РЕКОМЕНДАЦИЯ', 'ҰСЫНЫМ', 'RECOMMENDATION'],
  'src.data': ['ДАННЫЕ', 'ДЕРЕКТЕР', 'DATA'],
  'src.derived': ['ВЫВОД ПРАВИЛ', 'ЕРЕЖЕ ҚОРЫТЫНДЫСЫ', 'RULE-DERIVED'],
  'src.unknown': ['НЕИЗВЕСТНО', 'БЕЛГІСІЗ', 'UNKNOWN'],

  // уровни угрозы
  'threat.low': ['НИЗКИЙ', 'ТӨМЕН', 'LOW'],
  'threat.medium': ['СРЕДНИЙ', 'ОРТАША', 'MEDIUM'],
  'threat.high': ['ВЫСОКИЙ', 'ЖОҒАРЫ', 'HIGH'],
  'threat.critical': ['КРИТИЧЕСКИЙ', 'СЫНИ', 'CRITICAL'],
  'threat.label': ['Уровень угрозы', 'Қауіп деңгейі', 'Threat level'],

  // общие действия и слова
  'common.close': ['Закрыть', 'Жабу', 'Close'],
  'common.cancel': ['Отмена', 'Бас тарту', 'Cancel'],
  'common.retry': ['Повторить', 'Қайталау', 'Retry'],
  'common.back': ['Назад', 'Артқа', 'Back'],
  'common.save': ['Сохранить', 'Сақтау', 'Save'],
  'common.saved': ['Сохранено', 'Сақталды', 'Saved'],
  'common.copy': ['Копировать', 'Көшіру', 'Copy'],
  'common.copied': ['Скопировано', 'Көшірілді', 'Copied'],
  'common.print': ['Печать / Сохранить PDF', 'Басып шығару / PDF сақтау', 'Print / Save as PDF'],
  'common.download': ['Скачать', 'Жүктеу', 'Download'],
  'common.exportCsv': ['Экспорт CSV', 'CSV экспорты', 'Export CSV'],
  'common.all': ['Все', 'Барлығы', 'All'],
  'common.none': ['Нет', 'Жоқ', 'None'],
  'common.yes': ['Да', 'Иә', 'Yes'],
  'common.no': ['Нет', 'Жоқ', 'No'],
  'common.min': ['мин', 'мин', 'min'],
  'common.sec': ['с', 'с', 's'],
  'common.km': ['км', 'км', 'km'],
  'common.people': ['чел.', 'адам', 'people'],
  'common.loading': ['Загрузка…', 'Жүктелуде…', 'Loading…'],
  'common.analyzing': ['Анализ…', 'Талдау…', 'Analysing…'],
  'common.search': ['Поиск', 'Іздеу', 'Search'],
  'common.select': ['Выбрать', 'Таңдау', 'Select'],
  'common.details': ['Подробнее', 'Толығырақ', 'Details'],
  'common.status': ['Статус', 'Мәртебе', 'Status'],
  'common.region': ['Регион', 'Өңір', 'Region'],
  'common.city': ['Город', 'Қала', 'City'],
  'common.date': ['Дата', 'Күні', 'Date'],
  'common.time': ['Время', 'Уақыты', 'Time'],
  'common.source': ['Источник', 'Дереккөз', 'Source'],
  'common.updated': ['Обновлено', 'Жаңартылды', 'Updated'],
  'common.newRecord': ['новая', 'жаңа', 'new'],
  'common.page': ['Стр. {p} из {n}', '{n} беттің {p}-беті', 'Page {p} of {n}'],
  'common.prev': ['Назад', 'Алдыңғы', 'Previous'],
  'common.next': ['Далее', 'Келесі', 'Next'],
  'common.contentRu': ['Содержание DEMO-движка формируется на русском языке. В LIVE-режиме модель отвечает на выбранном языке.', 'DEMO-қозғалтқыш мазмұны орыс тілінде қалыптасады. LIVE режимінде модель таңдалған тілде жауап береді.', 'The DEMO engine produces this content in Russian. In LIVE mode the model answers in the selected language.'],
  'common.demoData': ['DEMO-данные', 'DEMO-деректер', 'DEMO data'],
  'common.notOfficial': ['Не является официальной информацией МЧС РК', 'ҚР ТЖМ ресми ақпараты болып табылмайды', 'Not official MChS RK information'],

  // ошибки и пустые состояния
  'err.title': ['Не удалось выполнить запрос', 'Сұрауды орындау мүмкін болмады', 'The request failed'],
  'err.noSubstitute': ['Демонстрационные данные не подставляются вместо реального ответа.', 'Нақты жауаптың орнына демо-деректер қойылмайды.', 'Demo data is never substituted for a real answer.'],
  'err.backendDown': ['Backend недоступен. Запустите сервер (npm run server:dev) или включите DEMO MODE.', 'Backend қолжетімсіз. Серверді іске қосыңыз (npm run server:dev) немесе DEMO MODE қосыңыз.', 'Backend unavailable. Start the server (npm run server:dev) or enable DEMO MODE.'],
  'err.empty': ['Backend вернул пустой или некорректный ответ', 'Backend бос немесе қате жауап қайтарды', 'The backend returned an empty or invalid response'],
  'err.ops': ['Оперативные данные недоступны', 'Жедел деректер қолжетімсіз', 'Operational data unavailable'],
  'empty.opsTitle': ['Источник оперативных данных не подключен', 'Жедел деректер көзі қосылмаған', 'No operational data source is connected'],
  'empty.opsText': ['Подключите OPERATIONAL_DATA_URL на backend. Демонстрационные данные в LIVE-режиме не показываются.', 'Backend-те OPERATIONAL_DATA_URL қосыңыз. LIVE режимінде демо-деректер көрсетілмейді.', 'Configure OPERATIONAL_DATA_URL on the backend. Demo data is not shown in LIVE mode.'],
  'empty.noIncidents': ['Активных происшествий нет', 'Белсенді оқиғалар жоқ', 'No active incidents'],

  // AI-безопасность и оговорки
  'safety.notice': ['Сформировано AI в целях обучения и информационной поддержки. Руководствуйтесь действующими официальными процедурами МЧС РК и указаниями ответственного руководителя.', 'AI оқыту және ақпараттық қолдау мақсатында қалыптастырды. ҚР ТЖМ-нің қолданыстағы ресми рәсімдерін және жауапты басшының нұсқауларын басшылыққа алыңыз.', "AI-generated training/information assistance. Follow current official MChS RK procedures and the responsible commander's instructions."],
  'safety.title': ['AI не является органом МЧС РК', 'AI ҚР ТЖМ органы емес', 'The AI is not an MChS RK authority'],
  'disclaimer.title': ['Рекомендации носят справочный характер.', 'Ұсынымдар анықтамалық сипатта.', 'Recommendations are for reference only.'],
  'disclaimer.text': ['Они не заменяют официальные оперативные документы, решения руководителя ликвидации ЧС (РТП) и действующие нормативные акты МЧС РК.', 'Олар ресми жедел құжаттарды, ТЖ жою басшысының шешімдерін және ҚР ТЖМ-нің қолданыстағы нормативтік актілерін алмастырмайды.', 'They do not replace official operational documents, the incident commander’s decisions or current MChS RK regulations.'],
  'pipeline.aria': ['Этапы обработки', 'Өңдеу кезеңдері', 'Processing stages'],

  // карта
  'map.offlineTitle': ['Картографическая подложка недоступна', 'Картографиялық негіз қолжетімсіз', 'Base map unavailable'],
  'map.offlineText': ['Офлайн-режим: показан схематичный контур РК и объекты. Для закрытой сети задайте VITE_MAP_TILE_URL.', 'Офлайн режимі: ҚР-дың сызбалық контуры мен нысандар көрсетілген. Жабық желі үшін VITE_MAP_TILE_URL орнатыңыз.', 'Offline mode: a schematic outline of Kazakhstan and objects are shown. For a closed network set VITE_MAP_TILE_URL.'],
  'map.aria': ['Карта Республики Казахстан', 'Қазақстан Республикасының картасы', 'Map of the Republic of Kazakhstan'],
} as const;
