/** Оперативная обстановка, AI RISK CENTER, карта ЧС. [ru, kz, en] */
export const dashboard = {
  'dash.title': ['Оперативная обстановка', 'Жедел жағдай', 'Operations overview'],
  'dash.subtitle': ['Происшествия, силы и риски на территории Республики Казахстан', 'Қазақстан Республикасы аумағындағы оқиғалар, күштер және тәуекелдер', 'Incidents, forces and risks across the Republic of Kazakhstan'],
  'dash.openMap': ['Карта ЧС', 'ТЖ картасы', 'Emergency map'],
  'dash.kpi.active': ['Активные ЧС', 'Белсенді ТЖ', 'Active incidents'],
  'dash.kpi.activeNote': ['по данным источника', 'дереккөз бойынша', 'per data source'],
  'dash.kpi.fires': ['Пожары', 'Өрттер', 'Fires'],
  'dash.kpi.firesNote': ['включая локализованные', 'оқшауланғандарды қоса', 'including contained'],
  'dash.kpi.rescues': ['Спасательные работы', 'Құтқару жұмыстары', 'Rescue operations'],
  'dash.kpi.rescuesNote': ['ДТП и паводки', 'ЖКО және су тасқындары', 'road accidents and floods'],
  'dash.kpi.units': ['Силы в работе', 'Жұмыстағы күштер', 'Units committed'],
  'dash.kpi.unitsNote': ['на месте и в пути', 'орнында және жолда', 'on scene and en route'],
  'dash.kpi.available': ['Доступно', 'Қолжетімді', 'Available'],
  'dash.kpi.availableNote': ['единиц в готовности', 'дайындықтағы бірлік', 'units ready'],
  'dash.mapTitle': ['Карта происшествий РК', 'ҚР оқиғалар картасы', 'Kazakhstan incident map'],
  'dash.showUnits': ['Показать силы', 'Күштерді көрсету', 'Show units'],
  'dash.aiTitle': ['AI-анализ обстановки', 'Жағдайды AI-талдау', 'AI situation analysis'],
  'dash.aiLoading': ['Модель анализирует обстановку…', 'Модель жағдайды талдауда…', 'The model is analysing the situation…'],
  'dash.forecast': ['Вероятное направление', 'Ықтимал бағыт', 'Likely direction'],
  'dash.forces': ['Рекомендуемые силы', 'Ұсынылатын күштер', 'Recommended forces'],
  'dash.monitoring': ['Нужен мониторинг', 'Бақылау қажет', 'Monitoring required'],
  'dash.factors': ['Ключевые факторы', 'Негізгі факторлар', 'Key factors'],
  'dash.detailed': ['Подробный анализ', 'Толық талдау', 'Detailed analysis'],
  'dash.toBriefing': ['AI-брифинг', 'AI-брифинг', 'AI briefing'],
  'dash.toResources': ['Подобрать силы', 'Күштерді таңдау', 'Plan resources'],
  'dash.detailLoading': ['Формирование подробного анализа…', 'Толық талдау қалыптастырылуда…', 'Preparing detailed analysis…'],
  'dash.detailForecast': ['Прогноз развития', 'Даму болжамы', 'Forecast'],
  'dash.detailRisks': ['Риски', 'Тәуекелдер', 'Risks'],
  'dash.detailRecs': ['Рекомендации', 'Ұсынымдар', 'Recommendations'],
  'dash.feed': ['Лента происшествий', 'Оқиғалар таспасы', 'Incident feed'],
  'dash.unitsAtWork': ['Силы в работе', 'Жұмыстағы күштер', 'Units at work'],
  'dash.closePanel': ['Закрыть панель', 'Панельді жабу', 'Close panel'],
  // статусы единиц
  'unit.available': ['Доступна', 'Қолжетімді', 'Available'],
  'unit.en_route': ['В пути', 'Жолда', 'En route'],
  'unit.on_scene': ['На месте', 'Орнында', 'On scene'],
  'unit.returning': ['Возвращается', 'Қайтуда', 'Returning'],
  'unit.maintenance': ['ТО / ремонт', 'ТҚ / жөндеу', 'Maintenance'],
  // risk center
  'risk.title': ['AI RISK CENTER', 'AI RISK CENTER', 'AI RISK CENTER'],
  'risk.updated': ['Обновлено: {d} · индексы 0–100 — справочная модель, не официальный прогноз', 'Жаңартылды: {d} · 0–100 индекстер — анықтамалық модель, ресми болжам емес', 'Updated: {d} · 0–100 indices are a reference model, not an official forecast'],
  'risk.fire': ['Пожарный риск', 'Өрт қаупі', 'Fire risk'],
  'risk.flood': ['Паводки и сели', 'Су тасқыны мен сел', 'Floods and mudflows'],
  'risk.weather': ['Метеориск', 'Метеотәуекел', 'Weather risk'],
  'risk.hazmat': ['Опасные объекты', 'Қауіпті нысандар', 'Hazardous facilities'],
  'risk.max': ['макс. · {r}', 'ең жоғары · {r}', 'max · {r}'],
  'risk.avg': ['Средний индекс {a} · высокий риск: {n} рег.', 'Орташа индекс {a} · жоғары тәуекел: {n} өңір', 'Average index {a} · high risk: {n} regions'],
  'risk.mapTitle': ['Карта рисков: {k}', 'Тәуекелдер картасы: {k}', 'Risk map: {k}'],
  'risk.alerts': ['Текущие предупреждения', 'Ағымдағы ескертулер', 'Current alerts'],
  'risk.top': ['Регионы с наибольшим риском', 'Тәуекелі ең жоғары өңірлер', 'Highest-risk regions'],
  'risk.none': ['AI RISK CENTER: источник данных о рисках не подключен', 'AI RISK CENTER: тәуекелдер туралы деректер көзі қосылмаған', 'AI RISK CENTER: no risk data source connected'],
  'risk.l1': ['Низкий', 'Төмен', 'Low'],
  'risk.l2': ['Умеренный', 'Қалыпты', 'Moderate'],
  'risk.l3': ['Повышенный', 'Жоғарылаған', 'Elevated'],
  'risk.l4': ['Высокий', 'Жоғары', 'High'],
  'risk.l5': ['Чрезвычайный', 'Төтенше', 'Extreme'],
  // карта ЧС
  'map.title': ['Карта чрезвычайных ситуаций', 'Төтенше жағдайлар картасы', 'Emergency map'],
  'map.subtitle': ['Происшествия, подразделения, больницы и водоисточники РК', 'ҚР оқиғалары, бөлімшелері, ауруханалары және су көздері', 'Incidents, units, hospitals and water sources in Kazakhstan'],
  'map.filters': ['Слои', 'Қабаттар', 'Layers'],
  'map.search': ['Поиск по названию или региону', 'Атауы немесе өңірі бойынша іздеу', 'Search by name or region'],
  'map.reset': ['Вся РК', 'Бүкіл ҚР', 'All Kazakhstan'],
  'map.list': ['Объекты ({n})', 'Нысандар ({n})', 'Objects ({n})'],
  'map.nothing': ['Ничего не найдено', 'Ештеңе табылмады', 'Nothing found'],
  'map.nearest': ['Ближайшие ресурсы', 'Жақын ресурстар', 'Nearest resources'],
  'map.distance': ['≈ {d} км по прямой', 'түзу бойынша ≈ {d} км', '≈ {d} km straight-line'],
  'map.select': ['Выберите объект на карте или в списке', 'Картадан немесе тізімнен нысанды таңдаңыз', 'Select an object on the map or in the list'],
  'map.cities': ['Города', 'Қалалар', 'Cities'],
} as const;
