/** AI OPERATIONAL BRIEFING и RESOURCE MANAGER. [ru, kz, en] */
export const ops = {
  'brief.title': ['AI OPERATIONAL BRIEFING', 'AI OPERATIONAL BRIEFING', 'AI OPERATIONAL BRIEFING'],
  'brief.subtitle': ['Структурированный брифинг для руководителя: факты — из данных, выводы и пробелы помечены', 'Басшыға арналған құрылымдық брифинг: фактілер — деректерден, қорытындылар мен олқылықтар белгіленген', 'Structured briefing for the commander: facts come from data; inferences and gaps are labelled'],
  'brief.source': ['Источник данных', 'Деректер көзі', 'Data source'],
  'brief.fromList': ['Выбрать происшествие', 'Оқиғаны таңдау', 'Select an incident'],
  'brief.manual': ['Ввести вручную', 'Қолмен енгізу', 'Enter manually'],
  'brief.incident': ['Происшествие', 'Оқиға', 'Incident'],
  'brief.generate': ['Сформировать брифинг', 'Брифинг құру', 'Generate briefing'],
  'brief.generating': ['Формирование брифинга…', 'Брифинг құрылуда…', 'Generating briefing…'],
  'brief.empty': ['Выберите происшествие и нажмите «Сформировать брифинг».', 'Оқиғаны таңдап, «Брифинг құру» түймесін басыңыз.', 'Select an incident and press "Generate briefing".'],
  'brief.f.type': ['Тип', 'Түрі', 'Type'],
  'brief.f.title': ['Краткое название', 'Қысқаша атауы', 'Short title'],
  'brief.f.city': ['Населенный пункт', 'Елді мекен', 'Settlement'],
  'brief.f.desc': ['Что произошло', 'Не болды', 'What happened'],
  'brief.f.threat': ['Оценка угрозы (оператор)', 'Қауіпті бағалау (оператор)', 'Threat estimate (operator)'],
  'brief.f.known': ['Людей известно', 'Белгілі адамдар', 'People known'],
  'brief.f.atRisk': ['В зоне опасности', 'Қауіпті аймақта', 'In danger zone'],
  'brief.f.injured': ['Пострадавшие', 'Зардап шеккендер', 'Injured'],
  'brief.f.evacuated': ['Эвакуировано', 'Көшірілді', 'Evacuated'],
  'brief.f.hint': ['Пустые поля остаются неизвестными — брифинг покажет их как информационные пробелы.', 'Бос өрістер белгісіз болып қалады — брифинг оларды ақпараттық олқылық ретінде көрсетеді.', 'Empty fields stay unknown — the briefing lists them as information gaps.'],
  'brief.f.required': ['Укажите название и описание', 'Атауы мен сипаттамасын көрсетіңіз', 'Enter a title and description'],
  'brief.s.situation': ['ОБСТАНОВКА', 'ЖАҒДАЙ', 'SITUATION'],
  'brief.s.threats': ['УГРОЗЫ', 'ҚАУІПТЕР', 'THREATS'],
  'brief.s.people': ['ЛЮДИ', 'АДАМДАР', 'PEOPLE'],
  'brief.s.weather': ['ПОГОДА', 'АУА РАЙЫ', 'WEATHER'],
  'brief.s.resources': ['СИЛЫ И СРЕДСТВА', 'КҮШТЕР МЕН ҚҰРАЛДАР', 'RESOURCES'],
  'brief.s.priorities': ['ПРИОРИТЕТЫ', 'БАСЫМДЫҚТАР', 'PRIORITIES'],
  'brief.s.gaps': ['ИНФОРМАЦИОННЫЕ ПРОБЕЛЫ', 'АҚПАРАТТЫҚ ОЛҚЫЛЫҚТАР', 'INFORMATION GAPS'],
  'brief.s.questions': ['ВОПРОСЫ ДЛЯ РУКОВОДИТЕЛЯ', 'БАСШЫҒА АРНАЛҒАН СҰРАҚТАР', 'QUESTIONS FOR COMMANDER'],
  'brief.narrative': ['Связное резюме (текст модели, проверен на соответствие данным)', 'Байланысты түйіндеме (модель мәтіні, деректерге сәйкестігі тексерілген)', 'Narrative summary (model text, checked against the data)'],
  'brief.generated': ['Сформирован: {d}', 'Құрылды: {d}', 'Generated: {d}'],
  'brief.legend': ['Метки: ДАННЫЕ — из структурированных данных; ВЫВОД ПРАВИЛ — учебные правила прототипа; НЕИЗВЕСТНО — требует уточнения.', 'Белгілер: ДЕРЕКТЕР — құрылымдық деректерден; ЕРЕЖЕ ҚОРЫТЫНДЫСЫ — прототиптің оқу ережелері; БЕЛГІСІЗ — нақтылауды қажет етеді.', 'Labels: DATA — from structured data; RULE-DERIVED — prototype training rules; UNKNOWN — needs clarification.'],
  'brief.doc': ['Оперативный брифинг', 'Жедел брифинг', 'Operational briefing'],
  'brief.toResources': ['Открыть расчет сил', 'Күштер есебін ашу', 'Open resource plan'],

  'res.title': ['RESOURCE MANAGER', 'RESOURCE MANAGER', 'RESOURCE MANAGER'],
  'res.subtitle': ['Силы и средства условных региональных подразделений: статус, место, назначение и DEMO-оптимизация', 'Шартты өңірлік бөлімшелердің күштері мен құралдары: мәртебе, орны, тағайындалуы және DEMO-оңтайландыру', 'Forces of notional regional departments: status, location, assignment and DEMO optimisation'],
  'res.demoRec': ['DEMO-РЕКОМЕНДАЦИЯ — НЕ ЯВЛЯЕТСЯ ОПЕРАТИВНОЙ КОМАНДОЙ', 'DEMO-ҰСЫНЫМ — ЖЕДЕЛ БҰЙРЫҚ ЕМЕС', 'DEMO RECOMMENDATION — NOT AN OPERATIONAL COMMAND'],
  'res.demoRecText': ['Расчет выполнен учебным алгоритмом по расстоянию и доступности. Решение о направлении сил принимает диспетчер и ответственный руководитель.', 'Есеп оқу алгоритмімен қашықтық пен қолжетімділік бойынша жасалды. Күштерді жіберу туралы шешімді диспетчер мен жауапты басшы қабылдайды.', 'Calculated by a training algorithm using distance and availability. Dispatch decisions rest with the dispatcher and the responsible commander.'],
  'res.optimize': ['Оптимизация развертывания', 'Орналастыруды оңтайландыру', 'Deployment optimisation'],
  'res.selectIncident': ['Происшествие для расчета', 'Есепке арналған оқиға', 'Incident to plan for'],
  'res.calc': ['Рассчитать', 'Есептеу', 'Calculate'],
  'res.requirements': ['Требуемые силы (учебные правила)', 'Қажетті күштер (оқу ережелері)', 'Required forces (training rules)'],
  'res.suggested': ['Предлагаемые единицы', 'Ұсынылатын бірліктер', 'Suggested units'],
  'res.shortage': ['Нехватка', 'Жетіспеушілік', 'Shortage'],
  'res.noShortage': ['Потребность закрыта доступными силами', 'Қажеттілік қолжетімді күштермен жабылды', 'All requirements covered by available units'],
  'res.totalCrew': ['Личный состав', 'Жеке құрам', 'Personnel'],
  'res.maxEta': ['Последняя единица через', 'Соңғы бірлік келеді', 'Last unit arrives in'],
  'res.fuel': ['Условные расходы на топливо', 'Жанармайға шартты шығын', 'Notional fuel cost'],
  'res.assumptions': ['Допущения расчета', 'Есептің болжамдары', 'Calculation assumptions'],
  'res.col.callsign': ['Позывной', 'Шақыру белгісі', 'Callsign'],
  'res.col.kind': ['Тип', 'Түрі', 'Type'],
  'res.col.status': ['Статус', 'Мәртебе', 'Status'],
  'res.col.dept': ['Подразделение', 'Бөлімше', 'Department'],
  'res.col.location': ['Место', 'Орны', 'Location'],
  'res.col.crew': ['Л/с', 'Ж/қ', 'Crew'],
  'res.col.assignment': ['Задача', 'Міндеті', 'Assignment'],
  'res.col.distance': ['Расстояние', 'Қашықтық', 'Distance'],
  'res.col.eta': ['Прибытие', 'Келуі', 'ETA'],
  'res.inventory': ['Реестр сил и средств', 'Күштер мен құралдар тізілімі', 'Unit register'],
  'res.filterKind': ['Все типы', 'Барлық түрлері', 'All types'],
  'res.filterStatus': ['Все статусы', 'Барлық мәртебелер', 'All statuses'],
  'res.filterRegion': ['Все регионы', 'Барлық өңірлер', 'All regions'],
  'res.searchCallsign': ['Позывной', 'Шақыру белгісі', 'Callsign'],
  'res.availableOf': ['доступно {a} из {n}', '{n}-ден {a} қолжетімді', '{a} of {n} available'],
  'res.none': ['Данные о силах и средствах не подключены', 'Күштер мен құралдар туралы деректер қосылмаған', 'No force/resource data connected'],
  'res.noneText': ['В LIVE-режиме список приходит из оперативного источника (поле units).', 'LIVE режимінде тізім жедел дереккөзден келеді (units өрісі).', 'In LIVE mode the list comes from the operational source (units field).'],
  'res.onMap': ['Схема развертывания', 'Орналастыру сызбасы', 'Deployment map'],
  'res.idle': ['—', '—', '—'],
  'res.remote': ['дальний резерв', 'алыс резерв', 'remote reserve'],
  'res.remoteNote': ['Часть единиц прибудет позже 60 мин — это дальний резерв, а не первый эшелон. Требуется привлечение местных сил.', 'Кейбір бірліктер 60 минуттан кейін келеді — бұл бірінші эшелон емес, алыс резерв. Жергілікті күштерді тарту қажет.', 'Some units arrive after 60 min — this is a remote reserve, not the first response. Local forces must be engaged.'],
} as const;
