/** Режим презентации. [ru, kz, en] */
export const presentation = {
  'pr.subtitle': ['Интеллектуальная поддержка спасательных подразделений · Республика Казахстан', 'Құтқару бөлімшелерін зияткерлік қолдау · Қазақстан Республикасы', 'Intelligent support for rescue units · Republic of Kazakhstan'],
  'pr.exit': ['Выйти (Esc)', 'Шығу (Esc)', 'Exit (Esc)'],
  'pr.fullscreen': ['Полный экран (F)', 'Толық экран (F)', 'Full screen (F)'],
  'pr.activeIncident': ['Активное происшествие', 'Белсенді оқиға', 'Active incident'],
  'pr.of': ['{i} из {n}', '{n}-ден {i}', '{i} of {n}'],
  'pr.prev': ['Предыдущее (←)', 'Алдыңғы (←)', 'Previous (←)'],
  'pr.next': ['Следующее (→)', 'Келесі (→)', 'Next (→)'],
  'pr.pause': ['Пауза автопрокрутки (Пробел)', 'Автоайналымды кідірту (Бос орын)', 'Pause auto-cycle (Space)'],
  'pr.play': ['Автопрокрутка (Пробел)', 'Автоайналым (Бос орын)', 'Auto-cycle (Space)'],
  'pr.ai': ['AI-анализ', 'AI-талдау', 'AI analysis'],
  'pr.risk': ['Уровень риска по РК', 'ҚР бойынша тәуекел деңгейі', 'Nationwide risk level'],
  'pr.forces': ['Силы и средства', 'Күштер мен құралдар', 'Forces and resources'],
  'pr.available': ['доступно', 'қолжетімді', 'available'],
  'pr.committed': ['в работе', 'жұмыста', 'committed'],
  'pr.events': ['Последние события', 'Соңғы оқиғалар', 'Recent events'],
  'pr.status': ['Состояние системы', 'Жүйе күйі', 'System status'],
  'pr.st.mode': ['Режим', 'Режим', 'Mode'],
  'pr.st.backend': ['Backend', 'Backend', 'Backend'],
  'pr.st.ai': ['AI-модель', 'AI-модель', 'AI model'],
  'pr.st.rag': ['Нормативная база', 'Нормативтік база', 'Regulations base'],
  'pr.st.data': ['Данные', 'Деректер', 'Data'],
  'pr.st.net': ['Сеть', 'Желі', 'Network'],
  'pr.v.demo': ['DEMO (офлайн)', 'DEMO (офлайн)', 'DEMO (offline)'],
  'pr.v.live': ['LIVE', 'LIVE', 'LIVE'],
  'pr.v.notUsed': ['не требуется', 'қажет емес', 'not required'],
  'pr.v.simulated': ['симуляция', 'модельдеу', 'simulated'],
  'pr.v.demoIndex': ['демо-индекс', 'демо-индекс', 'demo index'],
  'pr.v.demoData': ['вымышленные', 'ойдан шығарылған', 'fictional'],
  'pr.v.online': ['онлайн', 'онлайн', 'online'],
  'pr.v.offline': ['офлайн', 'офлайн', 'offline'],
  'pr.ev.dispatch': ['{u}: направлен — {i}', '{u}: жіберілді — {i}', '{u}: dispatched — {i}'],
  'pr.ev.onScene': ['{u}: прибыл на место — {i}', '{u}: орнына келді — {i}', '{u}: on scene — {i}'],
  'pr.ev.incident': ['Зарегистрировано: {i}', 'Тіркелді: {i}', 'Reported: {i}'],
  'pr.hint': ['← → происшествия · Пробел пауза · F полный экран · Esc выход', '← → оқиғалар · Бос орын кідірту · F толық экран · Esc шығу', '← → incidents · Space pause · F full screen · Esc exit'],
} as const;
