/** AI Emergency Simulator, режим инструктора, учебный отчет. [ru, kz, en] */
export const sim = {
  'sim.title': ['AI EMERGENCY SIMULATOR', 'AI EMERGENCY SIMULATOR', 'AI EMERGENCY SIMULATOR'],
  'sim.subtitle': ['Интерактивный тренажер принятия решений для спасателей и курсантов', 'Құтқарушылар мен курсанттарға арналған шешім қабылдаудың интерактивті тренажері', 'Interactive decision-making trainer for rescuers and cadets'],
  'sim.instructor': ['РЕЖИМ ИНСТРУКТОРА', 'НҰСҚАУШЫ РЕЖИМІ', 'INSTRUCTOR MODE'],
  'sim.trainee': ['Обучаемый (ФИО или позывной)', 'Тыңдаушы (аты-жөні немесе шақыру белгісі)', 'Trainee (name or call sign)'],
  'sim.traineePh': ['Например: курсант Абенов Н.', 'Мысалы: курсант Абенов Н.', 'e.g. Cadet Abenov N.'],
  'sim.intro': ['Вы — руководитель ликвидации ЧС. Обстановка развивается в реальном времени. Решения оценивает детерминированный движок правил; AI (при подключении) только озвучивает обстановку. Оценка — учебная.', 'Сіз — ТЖ жою басшысысыз. Жағдай нақты уақытта дамиды. Шешімдерді детерминирленген ережелер қозғалтқышы бағалайды; AI (қосылса) тек жағдайды сипаттайды. Баға — оқу бағасы.', 'You are the incident commander. The situation develops in real time. A deterministic rules engine scores your decisions; the AI (when connected) only narrates. The score is for training only.'],
  'sim.difficulty': ['Сложность', 'Күрделілік', 'Difficulty'],
  'sim.duration': ['Длительность', 'Ұзақтығы', 'Duration'],
  'sim.points': ['Точек решения', 'Шешім нүктелері', 'Decision points'],
  'sim.full': ['ПОЛНЫЙ СЦЕНАРИЙ', 'ТОЛЫҚ СЦЕНАРИЙ', 'FULL SCENARIO'],
  'sim.ruOnly': ['Повествование на русском', 'Баяндау орыс тілінде', 'Narrative in Russian'],
  'sim.toBriefing': ['К брифингу', 'Брифингке', 'To briefing'],
  'sim.generating': ['Генерация обстановки…', 'Жағдайды құру…', 'Generating the situation…'],
  'sim.briefing': ['Брифинг: {t}', 'Брифинг: {t}', 'Briefing: {t}'],
  'sim.ccTo': ['ЦУКС → РТП:', 'ДЖБО → ӨСБ:', 'Crisis centre → IC:'],
  'sim.aiNarr': ['AI-нарратив', 'AI-баяндау', 'AI narrative'],
  'sim.aiNarrNote': ['(текст модели; на оценку не влияет)', '(модель мәтіні; бағаға әсер етпейді)', '(model text; does not affect the score)'],
  'sim.place': ['Место происшествия', 'Оқиға орны', 'Location'],
  'sim.time': ['Время', 'Уақыты', 'Time'],
  'sim.weather': ['Погодные условия', 'Ауа райы жағдайлары', 'Weather'],
  'sim.people': ['Люди', 'Адамдар', 'People'],
  'sim.hazards': ['Известные опасности', 'Белгілі қауіптер', 'Known hazards'],
  'sim.forces': ['Доступные силы и средства', 'Қолжетімді күштер мен құралдар', 'Available forces and resources'],
  'sim.objectives': ['Учебные цели', 'Оқу мақсаттары', 'Training objectives'],
  'sim.chooseDiff': ['Уровень сложности', 'Күрделілік деңгейі', 'Difficulty level'],
  'sim.disclaimer': ['Сценарий учебный и вымышленный. Приемы и оценки тренажера не являются официальными нормативами МЧС РК. Вариант обстановки № {n} — скрытые условия меняются от варианта к варианту.', 'Сценарий оқу мақсатындағы және ойдан шығарылған. Тренажердің тәсілдері мен бағалары ҚР ТЖМ-нің ресми нормативтері емес. Жағдай нұсқасы № {n} — жасырын шарттар нұсқадан нұсқаға өзгереді.', 'The scenario is fictional and for training. Its techniques and scores are not official MChS RK standards. Situation variant #{n} — hidden conditions change between variants.'],
  'sim.other': ['Другой сценарий', 'Басқа сценарий', 'Another scenario'],
  'sim.start': ['НАЧАТЬ СИМУЛЯЦИЮ', 'СИМУЛЯЦИЯНЫ БАСТАУ', 'START SIMULATION'],
  'sim.initial': ['Исходная обстановка', 'Бастапқы жағдай', 'Initial situation'],
  'sim.simTime': ['Модельное время', 'Модельдік уақыт', 'Simulated time'],
  'sim.elapsed': ['Прошло', 'Өтті', 'Elapsed'],
  'sim.thinking': ['Время на решение', 'Шешімге уақыт', 'Decision time'],
  'sim.score': ['Учебная оценка', 'Оқу бағасы', 'Training score'],
  'sim.pause': ['Пауза', 'Кідірту', 'Pause'],
  'sim.resume': ['Продолжить', 'Жалғастыру', 'Resume'],
  'sim.finish': ['Завершить', 'Аяқтау', 'Finish'],
  'sim.paused': ['ПАУЗА — модельное время остановлено (разбор с инструктором).', 'КІДІРІС — модельдік уақыт тоқтатылды (нұсқаушымен талдау).', 'PAUSED — simulated time stopped (review with instructor).'],
  'sim.situation': ['Обстановка', 'Жағдай', 'Situation'],
  'sim.atRisk': ['В опасности', 'Қауіпте', 'At risk'],
  'sim.rescued': ['Спасено', 'Құтқарылды', 'Rescued'],
  'sim.lost': ['Погибло', 'Қаза тапты', 'Died'],
  'sim.scheme': ['Схема обстановки', 'Жағдай сызбасы', 'Situation map'],
  'sim.resources': ['Силы и средства', 'Күштер мен құралдар', 'Forces and resources'],
  'sim.committed': ['в работе {c} / {t}', 'жұмыста {c} / {t}', 'committed {c} / {t}'],
  'sim.currentEvent': ['ТЕКУЩЕЕ СОБЫТИЕ', 'АҒЫМДАҒЫ ОҚИҒА', 'CURRENT EVENT'],
  'sim.log': ['Ход событий', 'Оқиғалар барысы', 'Event log'],
  'sim.actions': ['ВАШИ ДЕЙСТВИЯ', 'СІЗДІҢ ӘРЕКЕТТЕРІҢІЗ', 'YOUR ACTIONS'],
  'sim.actionsHint': ['Выберите действие или введите собственную команду. Подсказок нет — оценка появится после решения.', 'Әрекетті таңдаңыз немесе өз командаңызды енгізіңіз. Кеңес жоқ — баға шешімнен кейін шығады.', 'Choose an action or type your own command. No hints — feedback appears after you decide.'],
  'sim.ownCmd': ['Своя команда', 'Өз команда', 'Your own command'],
  'sim.ownCmdPh': ['Напр.: направить 2 отделения на разведку', 'Мыс.: 2 бөлімшені барлауға жіберу', 'e.g. send two crews on reconnaissance'],
  'sim.sendCmd': ['Отдать команду', 'Команда беру', 'Issue command'],
  'sim.processing': ['Обработка', 'Өңдеу', 'Processing'],
  'sim.delta': ['{d} к оценке', 'бағаға {d}', '{d} to score'],
  'sim.decidedIn': ['решение за {s} с', 'шешім {s} с ішінде', 'decided in {s} s'],
  'sim.v.correct': ['Верное решение', 'Дұрыс шешім', 'Correct decision'],
  'sim.v.acceptable': ['Допустимо', 'Жол беріледі', 'Acceptable'],
  'sim.v.mistake': ['Тактическая ошибка', 'Тактикалық қате', 'Tactical mistake'],
  'sim.v.violation': ['Нарушение безопасности', 'Қауіпсіздікті бұзу', 'Safety violation'],
  'sim.v.unclear': ['Команда не распознана', 'Команда танылмады', 'Command not recognised'],
  'sim.ev.escalation': ['Ухудшение', 'Нашарлау', 'Escalation'],
  'sim.ev.improvement': ['Улучшение', 'Жақсару', 'Improvement'],
  'sim.ev.report': ['Разведданные', 'Барлау деректері', 'Intel'],
  'sim.ev.radio': ['Радиообмен', 'Радио алмасу', 'Radio'],
  'sim.ev.violation': ['Нарушение', 'Бұзушылық', 'Violation'],
  'sim.ev.decision': ['Решение РТП', 'ӨСБ шешімі', 'IC decision'],
  'sim.ev.info': ['Сводка', 'Жиынтық', 'Update'],
  'sim.diff.easy': ['Легкий', 'Жеңіл', 'Easy'],
  'sim.diff.medium': ['Средний', 'Орташа', 'Medium'],
  'sim.diff.hard': ['Сложный', 'Күрделі', 'Hard'],
  'sim.diff.expert': ['Эксперт', 'Сарапшы', 'Expert'],
  // разбор
  'sim.debrief': ['РАЗБОР СИМУЛЯЦИИ', 'СИМУЛЯЦИЯНЫ ТАЛДАУ', 'SIMULATION DEBRIEF'],
  'sim.debriefMeta': ['обучаемый: {n} · вариант № {s} · сложность: {d}', 'тыңдаушы: {n} · нұсқа № {s} · күрделілік: {d}', 'trainee: {n} · variant #{s} · difficulty: {d}'],
  'sim.outcome': ['Итог: {o}', 'Қорытынды: {o}', 'Outcome: {o}'],
  'sim.scoreOf': ['учебная оценка из 100', '100-ден оқу бағасы', 'training score out of 100'],
  'sim.scoreNote': ['Оценка учебная и формируется правилами тренажера. Она не является аттестацией, квалификационной оценкой или официальным заключением.', 'Баға оқу мақсатында, тренажер ережелерімен қалыптасады. Ол аттестация, біліктілік бағасы немесе ресми қорытынды емес.', 'This is a training score produced by the simulator rules. It is not a certification, qualification assessment or official finding.'],
  'sim.savedJournal': ['Результат сохранен в журнале инструктора.', 'Нәтиже нұсқаушы журналында сақталды.', 'Result saved to the instructor log.'],
  'sim.final': ['ИТОГОВЫЙ РЕЗУЛЬТАТ', 'ҚОРЫТЫНДЫ НӘТИЖЕ', 'FINAL RESULT'],
  'sim.objResult': ['Выполнение учебных целей', 'Оқу мақсаттарының орындалуы', 'Training objectives achieved'],
  'sim.objAchieved': ['достигнута', 'қол жеткізілді', 'achieved'],
  'sim.objMissed': ['не достигнута', 'қол жеткізілмеді', 'not achieved'],
  'sim.indicators': ['Показатели', 'Көрсеткіштер', 'Indicators'],
  'sim.i.decisions': ['Решений', 'Шешімдер', 'Decisions'],
  'sim.i.correct': ['Верных', 'Дұрыс', 'Correct'],
  'sim.i.acceptable': ['Допустимых', 'Жол берілген', 'Acceptable'],
  'sim.i.mistakes': ['Ошибок', 'Қателер', 'Mistakes'],
  'sim.i.violations': ['Нарушений', 'Бұзушылықтар', 'Violations'],
  'sim.i.unclear': ['Не распознано', 'Танылмады', 'Unrecognised'],
  'sim.i.avg': ['Среднее время', 'Орташа уақыт', 'Average time'],
  'sim.i.simMin': ['Модельное время', 'Модельдік уақыт', 'Simulated time'],
  'sim.decTimes': ['Время принятия решений', 'Шешім қабылдау уақыты', 'Decision times'],
  'sim.timeline': ['Хронология решений и событий', 'Шешімдер мен оқиғалар хронологиясы', 'Timeline of decisions and events'],
  'sim.icPrefix': ['РТП: ', 'ӨСБ: ', 'IC: '],
  'sim.correctList': ['Верные решения', 'Дұрыс шешімдер', 'Correct decisions'],
  'sim.correctNone': ['Верных решений не зафиксировано.', 'Дұрыс шешімдер тіркелмеді.', 'No correct decisions recorded.'],
  'sim.mistakeList': ['Ошибки и ухудшения обстановки', 'Қателер және жағдайдың нашарлауы', 'Mistakes and escalations'],
  'sim.mistakeNone': ['Ошибок не зафиксировано.', 'Қателер тіркелмеді.', 'No mistakes recorded.'],
  'sim.violList': ['Нарушения безопасности', 'Қауіпсіздікті бұзу', 'Safety violations'],
  'sim.violNone': ['Нарушений не зафиксировано.', 'Бұзушылықтар тіркелмеді.', 'No violations recorded.'],
  'sim.missedList': ['Упущенные возможности', 'Жіберілген мүмкіндіктер', 'Missed opportunities'],
  'sim.missedNone': ['Все ключевые действия выполнены.', 'Барлық негізгі әрекеттер орындалды.', 'All key actions completed.'],
  'sim.resUsage': ['Использование сил и средств', 'Күштер мен құралдарды пайдалану', 'Use of forces and resources'],
  'sim.resCol': ['Ресурс', 'Ресурс', 'Resource'],
  'sim.usedCol': ['Задействовано', 'Тартылды', 'Committed'],
  'sim.totalCol': ['Всего', 'Барлығы', 'Total'],
  'sim.recs': ['Анализ и рекомендации к тренировкам', 'Талдау және жаттығуға ұсынымдар', 'Analysis and training recommendations'],
  'sim.repeat': ['Повторить сценарий', 'Сценарийді қайталау', 'Repeat scenario'],
  'sim.chooseOther': ['Выбрать другой сценарий', 'Басқа сценарийді таңдау', 'Choose another scenario'],
  'sim.trainingReport': ['Учебный отчет', 'Оқу есебі', 'Training report'],
  'sim.radarAria': ['Профиль учебной оценки', 'Оқу бағасының профилі', 'Training score profile'],
  'cat.tactical': ['Тактические решения', 'Тактикалық шешімдер', 'Tactical decisions'],
  'cat.safety': ['Безопасность', 'Қауіпсіздік', 'Safety'],
  'cat.speed': ['Скорость реагирования', 'Ден қою жылдамдығы', 'Response speed'],
  'cat.resources': ['Управление ресурсами', 'Ресурстарды басқару', 'Resource management'],
  'cat.risk': ['Оценка рисков', 'Тәуекелді бағалау', 'Risk assessment'],
  'cat.interaction': ['Взаимодействие подразделений', 'Бөлімшелердің өзара іс-қимылы', 'Inter-unit coordination'],
  'cat.s.tactical': ['Такт.', 'Такт.', 'Tact.'],
  'cat.s.safety': ['Безоп.', 'Қауіпс.', 'Safety'],
  'cat.s.speed': ['Скор.', 'Жылд.', 'Speed'],
  'cat.s.resources': ['Ресурсы', 'Ресурс', 'Res.'],
  'cat.s.risk': ['Риски', 'Тәуекел', 'Risk'],
  'cat.s.interaction': ['Взаим.', 'Өзара', 'Coord.'],
  'grade.excellent': ['Отлично', 'Өте жақсы', 'Excellent'],
  'grade.good': ['Хорошо', 'Жақсы', 'Good'],
  'grade.satisfactory': ['Удовлетворительно', 'Қанағаттанарлық', 'Satisfactory'],
  'grade.retrain': ['Требуется повторная тренировка', 'Қайта жаттығу қажет', 'Retraining required'],
  // инструктор
  'ins.title': ['ПАНЕЛЬ ИНСТРУКТОРА', 'НҰСҚАУШЫ ПАНЕЛІ', 'INSTRUCTOR DASHBOARD'],
  'ins.note': ['Сессии на этом устройстве + демонстрационные курсанты (вымышлены, помечены DEMO). Учебные оценки, не аттестация.', 'Осы құрылғыдағы сессиялар + демо-курсанттар (ойдан шығарылған, DEMO белгісімен). Оқу бағалары, аттестация емес.', 'Sessions on this device plus demo trainees (fictional, marked DEMO). Training scores, not certification.'],
  'ins.clear': ['Очистить мои сессии', 'Менің сессияларымды тазарту', 'Clear my sessions'],
  'ins.f.scenario': ['Сценарий', 'Сценарий', 'Scenario'],
  'ins.f.trainee': ['Обучаемый', 'Тыңдаушы', 'Trainee'],
  'ins.f.difficulty': ['Сложность', 'Күрделілік', 'Difficulty'],
  'ins.f.from': ['С даты', 'Күннен бастап', 'From'],
  'ins.f.to': ['По дату', 'Күнге дейін', 'To'],
  'ins.f.reset': ['Сбросить фильтры', 'Сүзгілерді тазарту', 'Reset filters'],
  'ins.k.trainees': ['Обучаемых', 'Тыңдаушылар', 'Trainees'],
  'ins.k.sessions': ['Завершено сценариев', 'Аяқталған сценарийлер', 'Completed scenarios'],
  'ins.k.avg': ['Средняя учебная оценка', 'Орташа оқу бағасы', 'Average training score'],
  'ins.k.viol': ['Нарушений безопасности', 'Қауіпсіздікті бұзу', 'Safety violations'],
  'ins.k.time': ['Среднее время решения', 'Шешімнің орташа уақыты', 'Average decision time'],
  'ins.strong': ['Сильнейшая категория', 'Ең күшті санат', 'Strongest category'],
  'ins.weak': ['Слабейшая категория', 'Ең әлсіз санат', 'Weakest category'],
  'ins.catAvg': ['Средние по категориям (отфильтрованные сессии)', 'Санаттар бойынша орташа (сүзілген сессиялар)', 'Category averages (filtered sessions)'],
  'ins.trainees': ['Обучаемые', 'Тыңдаушылар', 'Trainees'],
  'ins.col.trainee': ['Обучаемый', 'Тыңдаушы', 'Trainee'],
  'ins.col.sessions': ['Сессий', 'Сессиялар', 'Sessions'],
  'ins.col.avg': ['Средняя', 'Орташа', 'Average'],
  'ins.col.best': ['Лучшая', 'Үздік', 'Best'],
  'ins.col.viol': ['Наруш.', 'Бұзу', 'Viol.'],
  'ins.col.avgTime': ['Ср. время', 'Орт. уақыт', 'Avg time'],
  'ins.col.weak': ['Слабое место', 'Әлсіз тұсы', 'Weak spot'],
  'ins.col.last': ['Последняя', 'Соңғы', 'Last'],
  'ins.history': ['История сценариев', 'Сценарийлер тарихы', 'Scenario history'],
  'ins.col.scenario': ['Сценарий', 'Сценарий', 'Scenario'],
  'ins.col.diff': ['Сложн.', 'Күрд.', 'Diff.'],
  'ins.col.score': ['Оценка', 'Баға', 'Score'],
  'ins.col.obj': ['Цели', 'Мақсаттар', 'Objectives'],
  'ins.col.grade': ['Итог', 'Қорытынды', 'Grade'],
  'ins.col.mistakes': ['Ошибки', 'Қателер', 'Mistakes'],
  'ins.col.duration': ['Время', 'Уақыт', 'Duration'],
  'ins.col.date': ['Дата', 'Күні', 'Date'],
  'ins.empty': ['Нет сессий по выбранным фильтрам.', 'Таңдалған сүзгілер бойынша сессиялар жоқ.', 'No sessions match the filters.'],
  'ins.detail': ['Детали сессии', 'Сессия мәліметтері', 'Session details'],
  'ins.decisions': ['Хронология решений', 'Шешімдер хронологиясы', 'Decision timeline'],
  'ins.noDecisions': ['Решений нет.', 'Шешімдер жоқ.', 'No decisions.'],
  'ins.detailMeta': ['Оценка {s} ({g}) · {o} · модельное время {m} мин · реальное {r}', 'Баға {s} ({g}) · {o} · модельдік уақыт {m} мин · нақты {r}', 'Score {s} ({g}) · {o} · simulated {m} min · real {r}'],
  'ins.demoRecord': ['DEMO-запись', 'DEMO-жазба', 'DEMO record'],
  // учебный отчет
  'tr.docTitle': ['QUTQAR AI — TRAINING REPORT', 'QUTQAR AI — TRAINING REPORT', 'QUTQAR AI — TRAINING REPORT'],
  'tr.docSubtitle': ['Отчет о прохождении учебного сценария (тренажер)', 'Оқу сценарийінен өту туралы есеп (тренажер)', 'Report on completion of a training scenario (simulator)'],
  'tr.id': ['ID отчета', 'Есеп ID', 'Report ID'],
  'tr.idNote': ['Внутренний идентификатор прототипа, не номер документа МЧС РК', 'Прототиптің ішкі идентификаторы, ҚР ТЖМ құжатының нөмірі емес', 'Internal prototype identifier, not an MChS RK document number'],
  'tr.qr': ['QR-заглушка: содержит ID отчета', 'QR-белгі: есеп ID-ін қамтиды', 'QR-style placeholder: encodes the report ID'],
  'tr.trainee': ['Обучаемый', 'Тыңдаушы', 'Trainee'],
  'tr.scenario': ['Сценарий', 'Сценарий', 'Scenario'],
  'tr.date': ['Дата', 'Күні', 'Date'],
  'tr.duration': ['Продолжительность', 'Ұзақтығы', 'Duration'],
  'tr.durationValue': ['{r} (реальное) · {m} мин (модельное)', '{r} (нақты) · {m} мин (модельдік)', '{r} (real) · {m} min (simulated)'],
  'tr.difficulty': ['Сложность', 'Күрделілік', 'Difficulty'],
  'tr.score': ['Итоговая учебная оценка', 'Қорытынды оқу бағасы', 'Final training score'],
  'tr.objectives': ['Учебные цели', 'Оқу мақсаттары', 'Training objectives'],
  'tr.categories': ['Оценка по категориям', 'Санаттар бойынша баға', 'Score by category'],
  'tr.decisions': ['Решения', 'Шешімдер', 'Decisions'],
  'tr.colT': ['Мин.', 'Мин.', 'Min'],
  'tr.colDecision': ['Решение', 'Шешім', 'Decision'],
  'tr.colVerdict': ['Оценка', 'Баға', 'Verdict'],
  'tr.colSec': ['Время, с', 'Уақыт, с', 'Time, s'],
  'tr.violations': ['Нарушения безопасности', 'Қауіпсіздікті бұзу', 'Safety violations'],
  'tr.outcome': ['Итог сценария', 'Сценарий қорытындысы', 'Scenario outcome'],
  'tr.recs': ['Рекомендации', 'Ұсынымдар', 'Recommendations'],
  'tr.footer': ['Документ сформирован прототипом QUTQAR AI в учебных целях (DEMO / TRAINING). Не является официальным документом МЧС РК, аттестацией или квалификационной оценкой.', 'Құжатты QUTQAR AI прототипі оқу мақсатында жасады (DEMO / TRAINING). ҚР ТЖМ ресми құжаты, аттестация немесе біліктілік бағасы емес.', 'Generated by the QUTQAR AI prototype for training (DEMO / TRAINING). Not an official MChS RK document, certification or qualification assessment.'],
  'tr.signTrainee': ['Обучаемый: ____________', 'Тыңдаушы: ____________', 'Trainee: ____________'],
  'tr.signInstructor': ['Инструктор: ____________', 'Нұсқаушы: ____________', 'Instructor: ____________'],
  'tr.out.success': ['Задача выполнена.', 'Міндет орындалды.', 'Objective achieved.'],
  'tr.out.partial': ['Истекло время учебного эпизода.', 'Оқу эпизодының уақыты бітті.', 'The training episode time ran out.'],
  'tr.out.failed': ['Травмирован личный состав.', 'Жеке құрам жарақат алды.', 'Personnel were injured.'],
  'tr.demoNames': ['Для DEMO-записей список решений условный.', 'DEMO-жазбалар үшін шешімдер тізімі шартты.', 'For DEMO records the decision list is notional.'],
} as const;
